# Generated by Django 5.2.6 on 2025-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
