# Generated by Django 5.2.6 on 2025-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_detection', '0002_alter_capture_photo_alter_capture_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='weapon_name',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='capture',
            name='weapon_number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
